# Generated by Django 3.1.7 on 2021-03-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3ImageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256, verbose_name='nombre del archivo')),
                ('image', models.ImageField(upload_to='images', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'imagen en S3',
                'verbose_name_plural': 'imagenes en S3',
            },
        ),
    ]
